# Milestone 1: Data Profiling

Profil awal dataset besar Indonesia menggunakan Polars LazyFrame dan DuckDB. Isi sumber serta deskripsi dataset pada `data/README.md` sebelum menjalankan notebook ini.

In [10]:

from pathlib import Path

import duckdb
import polars as pl

# Lokasi project
PROJECT_ROOT = Path.cwd().resolve().parent

# Lokasi dataset yang benar
DATA_PATH = PROJECT_ROOT / "data" / "raw" / "SFinDSet.csv"

if not DATA_PATH.is_file():
    raise FileNotFoundError(
        f"Dataset tidak ditemukan: {DATA_PATH}"
    )

print(f"Dataset: {DATA_PATH.name}")
print(f"Lokasi: {DATA_PATH}")
print(f"Ukuran file: {DATA_PATH.stat().st_size / 1_000_000:.1f} MB")

# Tes membaca dataset
df = pl.read_csv(DATA_PATH, n_rows=5)

print("\nDataset berhasil dibaca!")
print(df)

Dataset: SFinDSet.csv
Lokasi: /home/jovyan/work/data/raw/SFinDSet.csv
Ukuran file: 112.8 MB

Dataset berhasil dibaca!
shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Transacti ┆ Account_N ┆ Account_N ┆ Transacti ┆ … ┆ Transacti ┆ Transacti ┆ Transacti ┆ Transact │
│ on_ID     ┆ umber     ┆ ame       ┆ on_Amount ┆   ┆ on_Type   ┆ on_Date   ┆ on_Source ┆ ion_Dest │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ination  │
│ str       ┆ i64       ┆ str       ┆ f64       ┆   ┆ str       ┆ str       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ TRANS-588 ┆ 936832620 ┆ David     ┆ 1834602.8 ┆ … ┆ NGN to    ┆ 10/28/202 ┆ 169816110 ┆ 20322866 │
│ 469       ┆ 6         ┆ Howard    ┆           ┆   ┆ USD       ┆ 1 2:31    ┆ 4         ┆          │
│ TRANS-239 ┆ 682604575 ┆ David     ┆ 537724.4  ┆ … ┆ NGN to    ┆ 8/31/2022 ┆ 817277995 ┆ 20322866 │
│ 018       ┆ 8         ┆ Hughes    ┆           ┆   ┆ USD       ┆ 23:38     ┆ 6         ┆          │
│ TRANS-194 ┆ 538629991 ┆ David     ┆ 7.875963e ┆ … ┆ NGN to    ┆ 8/20/2023 ┆ 313897237 ┆ 20322866 │
│ 9426      ┆ 6         ┆ Huber     ┆ 6         ┆   ┆ USD       ┆ 8:56      ┆ 5         ┆          │
│ TRANS-158 ┆ 144356312 ┆ David     ┆ 2.0079e6  ┆ … ┆ NGN to    ┆ 2/13/2023 ┆ 969408011 ┆ 20322866 │
│ 8193      ┆ 4         ┆ Hunt      ┆           ┆   ┆ USD       ┆ 16:14     ┆ 8         ┆          │
│ TRANS-224 ┆ 724406018 ┆ David     ┆ 4.7660e7  ┆ … ┆ NGN to    ┆ 3/21/2021 ┆ 622568361 ┆ 20322866 │
│ 390       ┆ 3         ┆ Hughes    ┆           ┆   ┆ USD       ┆ 17:10     ┆ 9         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Profil Polars

`scan_parquet` hanya membangun rencana query; file baru dibaca ketika `collect()` dipanggil.

In [11]:

# Baca dataset CSV secara lazy
lazy_data = pl.scan_csv(DATA_PATH)

# Tampilkan struktur kolom dan tipe datanya
print(lazy_data.collect_schema())

# Hitung jumlah baris dan nilai null setiap kolom
ringkasan = lazy_data.select(
    [
        pl.len().alias("jumlah_baris"),
        *[
            pl.col(kolom).null_count().alias(f"{kolom}_null")
            for kolom in lazy_data.collect_schema().names()
        ],
    ]
).collect()

ringkasan

# Baca dataset CSV secara lazy
lazy_data = pl.scan_csv(DATA_PATH)

# Tampilkan struktur kolom dan tipe datanya
print(lazy_data.collect_schema())

# Hitung jumlah baris dan nilai null setiap kolom
ringkasan = lazy_data.select(
    [
        pl.len().alias("jumlah_baris"),
        *[
            pl.col(kolom).null_count().alias(f"{kolom}_null")
            for kolom in lazy_data.collect_schema().names()
        ],
    ]
).collect()

ringkasan

Schema({'Transaction_ID': String, 'Account_Number': Int64, 'Account_Name': String, 'Transaction_Amount': Float64, 'Transaction_Mode': String, 'Transaction_Type': String, 'Transaction_Date': String, 'Transaction_Source': Int64, 'Transaction_Destination': Int64})
Schema({'Transaction_ID': String, 'Account_Number': Int64, 'Account_Name': String, 'Transaction_Amount': Float64, 'Transaction_Mode': String, 'Transaction_Type': String, 'Transaction_Date': String, 'Transaction_Source': Int64, 'Transaction_Destination': Int64})

shape: (1, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ jumlah_ba ┆ Transacti ┆ Account_N ┆ Account_N ┆ … ┆ Transacti ┆ Transacti ┆ Transacti ┆ Transact │
│ ris       ┆ on_ID_nul ┆ umber_nul ┆ ame_null  ┆   ┆ on_Type_n ┆ on_Date_n ┆ on_Source ┆ ion_Dest │
│ ---       ┆ l         ┆ l         ┆ ---       ┆   ┆ ull       ┆ ull       ┆ _null     ┆ ination_ │
│ u32       ┆ ---       ┆ ---       ┆ u32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ null     │
│           ┆ u32       ┆ u32       ┆           ┆   ┆ u32       ┆ u32       ┆ u32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1048575   ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
# Ambil 10 baris pertama dari dataset
contoh_data = lazy_data.head(10).collect()

# Tampilkan hasilnya
contoh_data

shape: (10, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Transacti ┆ Account_N ┆ Account_N ┆ Transacti ┆ … ┆ Transacti ┆ Transacti ┆ Transacti ┆ Transact │
│ on_ID     ┆ umber     ┆ ame       ┆ on_Amount ┆   ┆ on_Type   ┆ on_Date   ┆ on_Source ┆ ion_Dest │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ination  │
│ str       ┆ i64       ┆ str       ┆ f64       ┆   ┆ str       ┆ str       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ TRANS-588 ┆ 936832620 ┆ David     ┆ 1834602.8 ┆ … ┆ NGN to    ┆ 10/28/202 ┆ 169816110 ┆ 20322866 │
│ 469       ┆ 6         ┆ Howard    ┆           ┆   ┆ USD       ┆ 1 2:31    ┆ 4         ┆          │
│ TRANS-239 ┆ 682604575 ┆ David     ┆ 537724.4  ┆ … ┆ NGN to    ┆ 8/31/2022 ┆ 817277995 ┆ 20322866 │
│ 018       ┆ 8         ┆ Hughes    ┆           ┆   ┆ USD       ┆ 23:38     ┆ 6         ┆          │
│ TRANS-194 ┆ 538629991 ┆ David     ┆ 7.875963e ┆ … ┆ NGN to    ┆ 8/20/2023 ┆ 313897237 ┆ 20322866 │
│ 9426      ┆ 6         ┆ Huber     ┆ 6         ┆   ┆ USD       ┆ 8:56      ┆ 5         ┆          │
│ TRANS-158 ┆ 144356312 ┆ David     ┆ 2.0079e6  ┆ … ┆ NGN to    ┆ 2/13/2023 ┆ 969408011 ┆ 20322866 │
│ 8193      ┆ 4         ┆ Hunt      ┆           ┆   ┆ USD       ┆ 16:14     ┆ 8         ┆          │
│ TRANS-224 ┆ 724406018 ┆ David     ┆ 4.7660e7  ┆ … ┆ NGN to    ┆ 3/21/2021 ┆ 622568361 ┆ 20322866 │
│ 390       ┆ 3         ┆ Hughes    ┆           ┆   ┆ USD       ┆ 17:10     ┆ 9         ┆          │
│ TRANS-123 ┆ 963385445 ┆ Howard    ┆ 1.1503e6  ┆ … ┆ NGN to    ┆ 6/3/2023  ┆ 786825359 ┆ 20322866 │
│ 9929      ┆ 7         ┆ Johnson   ┆           ┆   ┆ USD       ┆ 19:02     ┆ 4         ┆          │
│ TRANS-194 ┆ 386730764 ┆ Holly     ┆ 1139611.4 ┆ … ┆ NGN to    ┆ 3/19/2022 ┆ 414464418 ┆ 20322866 │
│ 7599      ┆           ┆ Williams  ┆           ┆   ┆ USD       ┆ 20:28     ┆ 2         ┆          │
│ TRANS-681 ┆ 483911413 ┆ Holly     ┆ 2735754.8 ┆ … ┆ NGN to    ┆ 11/24/202 ┆ 198256665 ┆ 20322866 │
│ 022       ┆ 3         ┆ Williams  ┆           ┆   ┆ USD       ┆ 1 23:57   ┆ 6         ┆          │
│ TRANS-198 ┆ 558229106 ┆ Holly     ┆ 3814374.1 ┆ … ┆ NGN to    ┆ 8/6/2022  ┆ 441339684 ┆ 20322866 │
│ 2400      ┆           ┆ Torres    ┆           ┆   ┆ USD       ┆ 20:35     ┆ 8         ┆          │
│ TRANS-501 ┆ 706519910 ┆ David     ┆ 3.0586e6  ┆ … ┆ NGN to    ┆ 11/15/202 ┆ 531803346 ┆ 20322866 │
│ 475       ┆ 5         ┆ Howard    ┆           ┆   ┆ USD       ┆ 0 4:57    ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Profil DuckDB

DuckDB membaca file Parquet langsung dari disk dan menghasilkan ringkasan statistik setiap kolom.

In [16]:

connection = duckdb.connect()

profil_duckdb = pl.from_pandas(
    connection.execute(
        "SUMMARIZE SELECT * FROM read_csv_auto(?)",
        [str(DATA_PATH)]
    ).fetchdf()
)

profil_duckdb

shape: (9, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ column_nam ┆ column_ty ┆ min       ┆ max       ┆ … ┆ q50       ┆ q75       ┆ count   ┆ null_perc │
│ e          ┆ pe        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---     ┆ entage    │
│ ---        ┆ ---       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ i64     ┆ ---       │
│ str        ┆ str       ┆           ┆           ┆   ┆           ┆           ┆         ┆ f64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ Transactio ┆ VARCHAR   ┆ TRANS-1   ┆ TRANS-999 ┆ … ┆ null      ┆ null      ┆ 1048575 ┆ 0.0       │
│ n_ID       ┆           ┆           ┆ 999       ┆   ┆           ┆           ┆         ┆           │
│ Account_Nu ┆ BIGINT    ┆ 500       ┆ 999999526 ┆ … ┆ 499775422 ┆ 749532301 ┆ 1048575 ┆ 0.0       │
│ mber       ┆           ┆           ┆ 4         ┆   ┆ 3         ┆ 1         ┆         ┆           │
│ Account_Na ┆ VARCHAR   ┆ Aaron     ┆ Zoe       ┆ … ┆ null      ┆ null      ┆ 1048575 ┆ 0.0       │
│ me         ┆           ┆ Abbott    ┆ Zavala    ┆   ┆           ┆           ┆         ┆           │
│ Transactio ┆ DOUBLE    ┆ 100.5     ┆ 49999946. ┆ … ┆ 4551908.6 ┆ 25055333. ┆ 1048575 ┆ 0.0       │
│ n_Amount   ┆           ┆           ┆ 5         ┆   ┆ 74472427  ┆ 532327898 ┆         ┆           │
│ Transactio ┆ VARCHAR   ┆ Card Out  ┆ Transfer  ┆ … ┆ null      ┆ null      ┆ 1048575 ┆ 0.0       │
│ n_Mode     ┆           ┆           ┆ Out       ┆   ┆           ┆           ┆         ┆           │
│ Transactio ┆ VARCHAR   ┆ NGN to    ┆ USD to    ┆ … ┆ null      ┆ null      ┆ 1048575 ┆ 0.0       │
│ n_Type     ┆           ┆ NGN       ┆ USD       ┆   ┆           ┆           ┆         ┆           │
│ Transactio ┆ VARCHAR   ┆ 1/1/2020  ┆ 9/9/2023  ┆ … ┆ null      ┆ null      ┆ 1048575 ┆ 0.0       │
│ n_Date     ┆           ┆ 0:01      ┆ 9:58      ┆   ┆           ┆           ┆         ┆           │
│ Transactio ┆ BIGINT    ┆ 12599     ┆ 999999951 ┆ … ┆ 499409097 ┆ 749491186 ┆ 1048575 ┆ 0.0       │
│ n_Source   ┆           ┆           ┆ 7         ┆   ┆ 0         ┆ 4         ┆         ┆           │
│ Transactio ┆ BIGINT    ┆ 4959      ┆ 999999754 ┆ … ┆ 499789817 ┆ 749573444 ┆ 1048575 ┆ 0.0       │
│ n_Destinat ┆           ┆           ┆ 9         ┆   ┆ 4         ┆ 3         ┆         ┆           │
│ ion        ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘

## Catatan Milestone 1 

Tulis temuan awal di bawah ini: ukuran data, jumlah baris, tipe kolom, kolom dengan null terbanyak, serta anomali yang perlu ditangani pada Milestone 2.

In [17]:

# Temuan awal dataset SFinDSet

# Ukuran file
ukuran_mb = DATA_PATH.stat().st_size / 1_000_000

# Jumlah baris dan tipe kolom
schema = lazy_data.collect_schema()
jumlah_baris = lazy_data.select(pl.len()).collect().item()
tipe_kolom = schema.dtypes()
nama_kolom = schema.names()

# Jumlah null setiap kolom
jumlah_null = lazy_data.select([
    pl.col(kolom).null_count().alias(kolom)
    for kolom in nama_kolom
]).collect()

null_dict = jumlah_null.row(0, named=True)
null_terbanyak = max(null_dict, key=null_dict.get)

print("=== TEMUAN AWAL DATASET SFinDSet ===")
print(f"Ukuran file       : {ukuran_mb:.2f} MB")
print(f"Jumlah baris      : {jumlah_baris:,}")
print(f"Jumlah kolom      : {len(nama_kolom)}")

print("\nTipe kolom:")
for nama, tipe in schema.items():
    print(f"- {nama}: {tipe}")

print("\nKolom dengan null terbanyak:")
print(f"- {null_terbanyak}: {null_dict[null_terbanyak]:,} null")

print("\nJumlah null per kolom:")
for kolom, jumlah in null_dict.items():
    print(f"- {kolom}: {jumlah:,}")

print("\nAnomali awal yang perlu diperiksa:")
print("- Nilai kosong (null) pada setiap kolom.")
print("- Duplikasi baris.")
print("- Ketidaksesuaian tipe data.")
print("- Nilai tidak valid atau di luar rentang yang wajar.")
print("- Format kategori dan teks yang tidak konsisten.")

=== TEMUAN AWAL DATASET SFinDSet ===
Ukuran file       : 112.80 MB
Jumlah baris      : 1,048,575
Jumlah kolom      : 9

Tipe kolom:
- Transaction_ID: String
- Account_Number: Int64
- Account_Name: String
- Transaction_Amount: Float64
- Transaction_Mode: String
- Transaction_Type: String
- Transaction_Date: String
- Transaction_Source: Int64
- Transaction_Destination: Int64

Kolom dengan null terbanyak:
- Transaction_ID: 0 null

Jumlah null per kolom:
- Transaction_ID: 0
- Account_Number: 0
- Account_Name: 0
- Transaction_Amount: 0
- Transaction_Mode: 0
- Transaction_Type: 0
- Transaction_Date: 0
- Transaction_Source: 0
- Transaction_Destination: 0

Anomali awal yang perlu diperiksa:
- Nilai kosong (null) pada setiap kolom.
- Duplikasi baris.
- Ketidaksesuaian tipe data.
- Nilai tidak valid atau di luar rentang yang wajar.
- Format kategori dan teks yang tidak konsisten.